spring.application.name=demo
spring.datasource.url=jdbc:sqlserver://localhost\\DATVUCNTTVA1:1433;database=GameForum;encrypt=false;trustServerCertificate=false
spring.datasource.username=vudat
spring.datasource.password=datvu2003
