spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.application.name=demo
spring.mvc.produces=application/json
spring.mvc.log-request-details=true

spring.datasource.url=jdbc:sqlserver://localhost\\DATVUCNTTVA1:1433;database=GameForum;encrypt=false;trustServerCertificate=false
spring.datasource.username=vudat
spring.datasource.password=datvu2003
spring.web.resources.static-locations=D:/hoctap/hoctap/web/uploads/,classpath:/static/

upload.dir=D:/hoctap/hoctap/web/uploads/

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

jwt.secret=ThisIsAVeryLongSecretKeyForJWTAuthentication1234567890abcdef
jwt.expirationInMs=3600000

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

server.port=8081
logging.level.org.springframework.security=DEBUG